version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - cov-configure --java
      - cov-configure --javascript
  build:
    commands:
      - echo Build started on `date`
      - cov-build --dir /root/coverity-idirs/jspwiki --return-emit-failures --delete-stale-tus mvn clean -Dmaven.test.skip=true install
  post_build:
    commands:
     - cov-analyze --dir /root/coverity-idirs/jspwiki
artifacts:
  files:
    - /coverity_output/**/* 
  discard-paths: no
